server.port=5000
spring.application.name=backend-dev-test
spring.data.mongodb.uri=mongodb://root:example@localhost:27017/backend-dev-test?authSource=admin
products-api.cache.base-url=http://localhost:3001
products-api.cache.ttl-ms=60000